services:
  - type: web
    name: super-idol
    env: python
    public: true
    buildCommand: >
      echo "開始構建過程" &&
      cd super-idol && npm install && npm run build && 
      echo "前端構建完成，檢查構建結果:" &&
      ls -la frontend/dist/ &&
      cd .. && 
      pip install -r requirements.txt
    startCommand: >
      cd super-idol/backend && 
      python -c "import os; os.makedirs('static', exist_ok=True); open('static/index.html', 'w').write('<html><body><h1>靜態文件測試頁面</h1></body></html>')" &&
      gunicorn --bind 0.0.0.0:$PORT --log-level debug run:app
    envVars:
      - key: DB_USER
        value: DBMS11302
      - key: DB_PASSWORD
        value: ilovedbms
      - key: DB_HOST
        value: superidol.c9i82eygu8mk.ap-southeast-2.rds.amazonaws.com
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: superidol
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: "https://super-idol.onrender.com"
      - key: LOG_LEVEL
        value: INFO
