services:
  - type: web
    name: super-idol
    env: python
    public: true
    buildCommand: >
      cd super-idol && npm install && npm run build && 
      ls -la frontend/dist/ &&
      mkdir -p backend/static && 
      cp -rv frontend/dist/* backend/static/ && 
      ls -la backend/static/ &&
      cd .. && 
      pip install -r requirements.txt
    startCommand: >
      cd super-idol && 
      mkdir -p backend/static && 
      cp -rv frontend/dist/* backend/static/ || echo "複製文件失敗，可能原因是前端尚未構建" && 
      ls -la backend/static/ && 
      cd backend && 
      gunicorn --bind 0.0.0.0:$PORT --log-level debug run:app
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
