services:
  - type: web
    name: super-idol
    env: python
    public: true
    buildCommand: >
      cd super-idol && npm install && npm run build && 
      mkdir -p backend/static && cp -r frontend/dist/* backend/static/ && 
      cd .. && pip install -r requirements.txt
    startCommand: cd super-idol/backend && gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
